[project]
name = "windows-record"
version = "0.1.0"
description = "A Python package for recording window on Windows"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.11.13",
]
